# Form implementation generated from reading ui file 'C:\Tiêu Đăng Vinh\Học máy trong kinh doanh\K22416C\salesmanagement\ui\MainProgramMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(773, 481)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 180, 631, 61))
        self.label.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(170, 255, 255);\n"
"font: 36pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 773, 26))
        self.menubar.setObjectName("menubar")
        self.menuhethong = QtWidgets.QMenu(parent=self.menubar)
        self.menuhethong.setObjectName("menuhethong")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionthongtintaikhoan = QtGui.QAction(parent=MainWindow)
        self.actionthongtintaikhoan.setCheckable(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Tiêu Đăng Vinh\\Học máy trong kinh doanh\\K22416C\\salesmanagement\\ui\\../images/8665306_circle_user_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.actionthongtintaikhoan.setIcon(icon)
        self.actionthongtintaikhoan.setShortcutContext(QtCore.Qt.ShortcutContext.WindowShortcut)
        self.actionthongtintaikhoan.setObjectName("actionthongtintaikhoan")
        self.actiondoimatkhau = QtGui.QAction(parent=MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Tiêu Đăng Vinh\\Học máy trong kinh doanh\\K22416C\\salesmanagement\\ui\\../images/1564520_code_open_password_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.actiondoimatkhau.setIcon(icon1)
        self.actiondoimatkhau.setObjectName("actiondoimatkhau")
        self.actioncauhinhhethong = QtGui.QAction(parent=MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Tiêu Đăng Vinh\\Học máy trong kinh doanh\\K22416C\\salesmanagement\\ui\\../images/299093_window_system_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.actioncauhinhhethong.setIcon(icon2)
        self.actioncauhinhhethong.setObjectName("actioncauhinhhethong")
        self.actionthoatphanmem = QtGui.QAction(parent=MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:\\Tiêu Đăng Vinh\\Học máy trong kinh doanh\\K22416C\\salesmanagement\\ui\\../images/Error.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.actionthoatphanmem.setIcon(icon3)
        self.actionthoatphanmem.setObjectName("actionthoatphanmem")
        self.menuhethong.addSeparator()
        self.menuhethong.addAction(self.actionthongtintaikhoan)
        self.menuhethong.addAction(self.actiondoimatkhau)
        self.menuhethong.addAction(self.actioncauhinhhethong)
        self.menuhethong.addAction(self.actionthoatphanmem)
        self.menubar.addAction(self.menuhethong.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Đây là màn hình chính"))
        self.menuhethong.setTitle(_translate("MainWindow", "Hệ thống"))
        self.actionthongtintaikhoan.setText(_translate("MainWindow", "Thông tin tài khoản"))
        self.actiondoimatkhau.setText(_translate("MainWindow", "Đổi mật khẩu"))
        self.actioncauhinhhethong.setText(_translate("MainWindow", "Cấu hình hệ thống"))
        self.actionthoatphanmem.setText(_translate("MainWindow", "Thoát phần mềm"))
